### ISSUE TITLE
Missing Quote

### ISSUE THREAD

**Issue by AdrieanKhisbe** [cedias/chirac#1]
[Quand on arrive pas à résoudre un problème, le mieux c'est de changer de problème](http://www.dailymotion.com/video/x9muhi_jacques-chirac-et-la-technologie-le_fun)

**Comment by cedias** [comment]
"This is not a method, this is provocation"

**Comment by AdrieanKhisbe** [comment]
"This is exactly the answer you are looking for" :D :dart:

**Comment by AdrieanKhisbe** [comment]
https://www.dailymotion.com/video/xa9r0y, au revoir
